// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_file_path_ from "./routes/api/file/[...path].ts";
import * as $api_manifest from "./routes/api/manifest.ts";
import * as $index from "./routes/index.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $PapersPanel from "./islands/PapersPanel.tsx";
import * as $PrimaryPanel from "./islands/PrimaryPanel.tsx";
import * as $Register from "./islands/Register.tsx";
import * as $ViewPanel from "./islands/ViewPanel.tsx";
import * as $ViewSection from "./islands/ViewSection.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/file/[...path].ts": $api_file_path_,
    "./routes/api/manifest.ts": $api_manifest,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Header.tsx": $Header,
    "./islands/PapersPanel.tsx": $PapersPanel,
    "./islands/PrimaryPanel.tsx": $PrimaryPanel,
    "./islands/Register.tsx": $Register,
    "./islands/ViewPanel.tsx": $ViewPanel,
    "./islands/ViewSection.tsx": $ViewSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
